VOTE/src/java/model/entity/Playground.java
package model.entity;

public class Playground extends AbstractEntity {

    private String name;
    private User creator;
    private boolean active;

    public Playground() {
    }

    public Playground(int id, String name, User creator, boolean active) {
        this.id = id;
        this.name = name;
        this.creator = creator;
        this.active = active;
    }

    public Playground(String name, User creator, boolean active) {
        this.name = name;
        this.creator = creator;
        this.active = active;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public User getCreator() {
        return creator;
    }

    public void setCreator(User creator) {
        this.creator = creator;
    }

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    @Override
    public String toString() {
        return "Playground{" + "id=" + id + ", name=" + name + ", creator=" + creator + ", active=" + active + '}';
    }

}

VOTE/src/java/view/beans/LoginView.java
package view.beans;

import controller.businessControllers.MainController;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;
import model.entity.Playground;
import model.entity.User;

@ManagedBean
@RequestScoped
public class LoginView {

    private String email;
    private String password;
    private final FacesMessage failedLoginMessage = new FacesMessage("Incorrect username or password");
    private final FacesMessage playgroundNotFoundMessage = new FacesMessage("Poll not found");
    private String uniqueCode;

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void validateLogin() {
        User user = MainController.getInstance().getLoginController().tryLogin(email, password);
        if (user != null) {
            HttpSession session = SessionUtils.getSession();
            session.setAttribute("user", user);
            SessionUtils.redirect("playgrounds");
        } else {
            FacesContext.getCurrentInstance().addMessage(null, failedLoginMessage);
        }
    }

    public String createUser() {
        return "newUser" + SessionUtils.REDIRECT_URL_SUFFIX;
    }

    public String getUniqueCode() {
        return uniqueCode;
    }

    public void setUniqueCode(String uniqueCode) {
        this.uniqueCode = uniqueCode;
    }

    public void goToUniqueCode() {
        if (uniqueCode == null || "".equals(uniqueCode)) {
            return;
        }
        int playgroundId = Integer.valueOf(uniqueCode) / PlaygroundView.PRIME_NUMBER;
        Playground playground = MainController.getInstance().getPlaygroundController().getPlaygroundById(playgroundId);
        if (playground != null) {
            SessionUtils.redirectToPlayground(playground);
        } else {
            FacesContext.getCurrentInstance().addMessage(null, playgroundNotFoundMessage);
        }
    }

}

VOTE/src/java/view/beans/NewPlaygroundView.java
package view.beans;

import controller.businessControllers.MainController;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import model.entity.Choice;
import model.entity.Playground;

@ManagedBean
@ViewScoped
public class NewPlaygroundView {

    private String playgroundName;
    private String choiceName;
    private Set<String> choices;

    @PostConstruct
    public void init() {
        playgroundName = "";
        choices = new LinkedHashSet<>();
    }

    public void addChoice() {
        if (!"".equals(choiceName) && choiceName != null) {
            choices.add(choiceName);
        }
        this.choiceName = "";
    }

    public void removeChoice(String choice) {
        choices.remove(choice);
    }

    public void save() {
        if ("".equals(playgroundName) || playgroundName == null) {
            return;
        }
        Playground playground = new Playground(playgroundName, SessionUtils.getSessionUser(), true);
        MainController.getInstance().getPlaygroundController().createPlayground(playground);
        choices.stream().map(x -> new Choice(playground, x))
                .forEach(x -> MainController.getInstance().getChoiceController().createChoice(x));
        SessionUtils.redirect("playgrounds");
    }

    public void back() {
        SessionUtils.redirect("playgrounds");
    }

    public String getPlaygroundName() {
        return playgroundName;
    }

    public void setPlaygroundName(String playgroundName) {
        this.playgroundName = playgroundName;
    }

    public String getChoiceName() {
        return choiceName;
    }

    public void setChoiceName(String choiceName) {
        this.choiceName = choiceName;
    }

    public Set<String> getChoices() {
        return choices;
    }

    public void setChoices(Set<String> choices) {
        this.choices = choices;
    }

}

VOTE/src/java/view/beans/NewUserView.java
package view.beans;

import controller.businessControllers.UserController;
import controller.businessControllers.MainController;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;
import model.entity.User;

@ManagedBean
@RequestScoped
public class NewUserView {

    private String email;
    private String password;
    private final FacesMessage failedLoginMessage = new FacesMessage("Email already exists!");

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void validateNewUser() {
        UserController loginController = MainController.getInstance().getLoginController();
        boolean emailIsFree = loginController.emailIsFree(email);
        if (emailIsFree) {
            User user = loginController.createUser(email, password);
            HttpSession session = SessionUtils.getSession();
            session.setAttribute("user", user);
            SessionUtils.redirect("playgrounds");
        } else {
            FacesContext.getCurrentInstance().addMessage(null, failedLoginMessage);
        }
    }

    public void cancel() {
        SessionUtils.redirect("login");
    }
}

VOTE/src/java/view/beans/PlaygroundView.java
package view.beans;

import controller.businessControllers.MainController;
import controller.businessControllers.VoteController;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;
import model.entity.Choice;
import model.entity.Playground;
import model.entity.Vote;

@ManagedBean
@ViewScoped
public class PlaygroundView {

    public static final int PRIME_NUMBER = 199;
    private Playground currentPlayground;
    private List<Choice> choices;
    private List<Vote> allVotes;
    private List<String> nicknames;
    private List<PlaygroundTableRow> rows;
    private Choice selectedChoice;

    @PostConstruct
    public void init() {
        int uniqueLink = Integer.valueOf(FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get("uniqueLink"));
        final MainController mainController = MainController.getInstance();
        currentPlayground = mainController.getPlaygroundController().getPlaygroundById(uniqueLink / PlaygroundView.PRIME_NUMBER);
        choices = mainController.getChoiceController().getChoicesForPlayground(currentPlayground);
        allVotes = new ArrayList<>();
        choices.stream().forEach(x -> allVotes.addAll(mainController.getVoteController().getVotesByChoice(x)));
        nicknames = allVotes.stream().map(x -> x.getNickname()).distinct().collect(Collectors.toList());
        Collections.sort(nicknames);
        rows = new ArrayList<>();
        nicknames.stream().forEach(x -> rows.add(new PlaygroundTableRow(x, choices, false)));

        for (PlaygroundTableRow row : rows) {
            String nickname = row.getNickname();
            Map<Choice, Boolean> choiceVoteBindings = row.getChoiceVoteBindings();
            List<Vote> votesForNickname = allVotes.stream().filter(x -> x.getNickname().equals(nickname)).collect(Collectors.toList());
            votesForNickname.stream().forEach(x -> choiceVoteBindings.put(x.getChoice(), Boolean.TRUE));
        }
        PlaygroundTableRow newRow = new PlaygroundTableRow("", choices, true);
        rows.add(newRow);

        HttpSession session = SessionUtils.getSession();
        if (SessionUtils.getSessionUser() == null) {
            session.setAttribute("tempUser", "tempUser");
        }
    }

    public Choice getSelectedChoice() {
        return selectedChoice;
    }

    public void setSelectedChoice(Choice selectedChoice) {
        this.selectedChoice = selectedChoice;
    }

    public Playground getCurrentPlayground() {
        return currentPlayground;
    }

    public void setCurrentPlayground(Playground currentPlayground) {
        this.currentPlayground = currentPlayground;
    }

    public List<Choice> getChoices() {
        return choices;
    }

    public void setChoices(List<Choice> choices) {
        this.choices = choices;
    }

    public List<Vote> getAllVotes() {
        return allVotes;
    }

    public void setAllVotes(List<Vote> allVotes) {
        this.allVotes = allVotes;
    }

    public List<String> getNicknames() {
        return nicknames;
    }

    public void setNicknames(List<String> nicknames) {
        this.nicknames = nicknames;
    }

    public List<PlaygroundTableRow> getRows() {
        return rows;
    }

    public void setRows(List<PlaygroundTableRow> rows) {
        this.rows = rows;
    }

    public void updateVote(String nickname, Choice choice, boolean voted) {
        if ("".equals(nickname) || nickname == null) {
            return;
        }
        for (PlaygroundTableRow row : rows) {
            if (row.getNickname().equals(nickname)) {
                row.getChoiceVoteBindings().put(choice, voted);
            }
        }
        VoteController voteController = MainController.getInstance().getVoteController();
        if (voted) {
            Vote vote = new Vote(choice, nickname);
            voteController.createVote(vote);
        } else {
            voteController.deleteVoteByChoiceAndNickname(choice, nickname);
        }
    }

    public String getUniqueLink() {
        return String.valueOf(currentPlayground.getId() * PlaygroundView.PRIME_NUMBER);

    }

    public void reload() {
        SessionUtils.redirectToPlayground(currentPlayground);
    }

    public void back() {
        SessionUtils.redirect("playgrounds");
    }

    public void toLogin() {
        SessionUtils.redirect("login");
    }

    public boolean isButtonBackVisible() {
        return SessionUtils.getSessionUser() != null;
    }
    
    public int getNumberOfVotesForChoice (Choice choice){
        return MainController.getInstance().getVoteController().getVotesByChoice(choice).size();
    }

}

VOTE/src/java/view/beans/PlaygroundsView.java
package view.beans;

import controller.businessControllers.ChoiceController;
import controller.businessControllers.MainController;
import controller.businessControllers.PlaygroundController;
import controller.businessControllers.VoteController;
import java.util.ArrayList;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import model.entity.Choice;
import model.entity.Playground;
import model.entity.User;
import model.entity.Vote;

@ManagedBean
@ViewScoped
public class PlaygroundsView {

    private User user;
    private List<Playground> playgrounds;
    private Playground selectedPlayground;
    private final FacesMessage failedLoginMessage = new FacesMessage("Incorrect username or password");

    public PlaygroundsView() {
        this.user = SessionUtils.getSessionUser();
        playgrounds = MainController.getInstance().getPlaygroundsController().getPlaygroundsForUser(user);
    }

    public void removePlayground(Playground playground) {
        PlaygroundController playgroundController = MainController.getInstance().getPlaygroundController();
        ChoiceController choiceController = MainController.getInstance().getChoiceController();
        VoteController voteController = MainController.getInstance().getVoteController();

        List<Choice> choices = choiceController.getChoicesForPlayground(playground);
        List<Vote> votes = new ArrayList<>();
        choices.stream().forEach(x -> votes.addAll(voteController.getVotesByChoice(x)));

        votes.stream().forEach(x -> voteController.deleteVote(x));
        choices.stream().forEach(x -> choiceController.removeChoice(x));
        playgroundController.deletePlayground(playground);

        playgrounds.remove(playground);
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public List<Playground> getPlaygrounds() {
        return playgrounds;
    }

    public void setPlaygrounds(List<Playground> playgrounds) {
        this.playgrounds = playgrounds;
    }

    public Playground getSelectedPlayground() {
        return selectedPlayground;
    }

    public void setSelectedPlayground(Playground selectedPlayground) {
        this.selectedPlayground = selectedPlayground;
    }

    public void navigateToPlayground() {
        SessionUtils.redirectToPlayground(selectedPlayground);
    }

    public void navigateToNewPlayground() {
        SessionUtils.redirect("newPlayground");
    }

    public String getSessionUser() {
        return SessionUtils.getSessionUser().getEmail();
    }
}

VOTE/src/java/controller/businessControllers/LoginController.java
package controller.businessControllers;

import model.entity.User;
import model.entity.dao.UserDAO;

public class LoginController {

  public User tryLogin(String email, String password) {
    if (email == null) {
      return null;
    }
    User user = new UserDAO().getUserByEmail(email);
    return user != null && password != null && password.equals(user.getPassword()) ? user : null;
  }

  public User createUser(String email, String password) {
    if (email == null || password == null) {
      return null;
    }

    User user = new User(password, email);

    if (emailIsFree(email)) {
      new UserDAO().create(user);
      return user;
    } else {
      return null;
    }
  }

  public boolean emailIsFree(String email) {
    return email != null && new UserDAO().getUserByEmail(email) == null;
  }

}

VOTE/src/java/controller/businessControllers/PlaygroundController.java
package controller.businessControllers;

import model.entity.Playground;
import model.entity.dao.PlaygroundDAO;

public class PlaygroundController {

    PlaygroundDAO playgroundDAO;

    public PlaygroundController() {
        playgroundDAO = new PlaygroundDAO();
    }

    public Playground getPlaygroundById(int id) {
        return playgroundDAO.getPlaygroundById(id);
    }

    public void createPlayground(Playground playground) {
        playgroundDAO.create(playground);
    }

    public void deletePlayground(Playground playground) {
        playgroundDAO.delete(playground);
    }

}

VOTE/src/java/controller/businessControllers/PlaygroundsController.java
package controller.businessControllers;

import java.util.List;
import model.entity.Playground;
import model.entity.User;
import model.entity.dao.PlaygroundDAO;

public class PlaygroundsController {

  PlaygroundDAO playgroundDAO;

  public PlaygroundsController() {
    playgroundDAO = new PlaygroundDAO();
  }

  public List<Playground> getPlaygroundsForUser(User user) {
    return playgroundDAO.getPlaygroundsForUser(user);
  }

}

VOTE/web/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>VOTE</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </h:head>
    <h:body>
        <h:outputStylesheet library="css" name="styles.css"/>
        <h:form>
            <div class="ui-g">
                <div class="ui-g-12">
                    <p:graphicImage name="images/network64.png" />
                    <h1>Welcome to VOTE</h1>
                </div>
            </div>
            <div class="ui-g">
                <div class="ui-g-12">
                    <h2>Log in</h2>
                </div>
            </div>
            <div class="ui-g">
                <div class="ui-g-12">
                    <p:inputText value="#{loginView.email}" placeholder="Username or e-mail"/>
                </div>
            </div>
            <div class="ui-g">
                <div class="ui-g-12">
                    <p:password value="#{loginView.password}" placeholder="Password"/>
                </div>
            </div>
            <div class="ui-g">
                <div class="ui-g-12">
                    <p:commandButton value="Log in" action="#{loginView.validateLogin()}"/>
                    <p:spacer width="20px"/>
                    <p:commandButton value="New user" action="#{loginView.createUser()}"/>
                </div>
            </div>
            <div class="ui-g">
                <div class="ui-g-12">
                    <p:messages autoUpdate="true"/>
                </div>
            </div>
            <div class="ui-g">
                <div class="ui-g-12">
                    <h2>...or insert a unique code</h2>
                </div>
            </div>
            <div class="ui-g">
                <div class="ui-g-12">
                    <p:inputText value="#{loginView.uniqueCode}" placeholder="Insert unique code"/>
                </div>
            </div>
            <div class="ui-g">
                <div class="ui-g-12">
                    <p:commandButton value="Go" action="#{loginView.goToUniqueCode()}"/>
                </div>
            </div>
        </h:form>
    </h:body>
</html>

VOTE/web/newPlayground.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>VOTE</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </h:head>
    <h:body>
        <h:outputStylesheet library="css" name="styles.css"/>
        <h:outputStylesheet name="webjars/font-awesome/4.4.0/css/font-awesome.css"/>
        <h:form id="newPlaygroundForm">
            <div class="ui-g">
                <div class="ui-g-12">
                    <p:graphicImage name="images/network64.png" />
                    <h1>New poll</h1>
                </div>
            </div>
            <div class="ui-g">
                <div class="ui-g-12">
                    <p:inputText placeholder="Poll name" value="#{newPlaygroundView.playgroundName}"/>
                </div>
            </div>
            <div class="ui-g">
                <div class="ui-g-12">
                    <p:inputText id="choiceName" placeholder="Add new choice" value="#{newPlaygroundView.choiceName}"/>
                </div>
                <div class="ui-g-12">
                    <p:commandButton value="Add choice" actionListener="#{newPlaygroundView.addChoice()}" style="width: 135px;"
                                     update=":newPlaygroundForm:newPlaygroundTable, :newPlaygroundForm:choiceName"/>
                </div>
            </div>
            <div class="ui-g">
                <div class="ui-g-12">
                    <p:dataTable id="newPlaygroundTable" var="choice" 
                                 value="#{newPlaygroundView.choices}"
                                 emptyMessage="No choices yet, add a new one!"
                                 style="max-width: 350px;">
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="Choices"/>
                            </f:facet>
                            <h:outputText value="#{choice}"/>
                            <p:commandButton icon="fa fa-remove" class="iconButton" actionListener="#{newPlaygroundView.removeChoice(choice)}" update=":newPlaygroundForm:newPlaygroundTable"/>
                        </p:column>
                    </p:dataTable>
                </div>
            </div>
            <div class="ui-g">
                <div class="ui-g-12">
                    <p:commandButton value="Save" action="#{newPlaygroundView.save()}"/>
                    <p:spacer width="20px"/>
                    <p:commandButton value="Back" action="#{newPlaygroundView.back()}"/>
                </div>
            </div>
        </h:form>
    </h:body>
</html>

VOTE/web/newUser.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>VOTE</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </h:head>
    <h:body>
        <h:outputStylesheet library="css" name="styles.css"/>
        <h:form>
            <div class="ui-g">
                <div class="ui-g-12">
                    <p:graphicImage name="images/network64.png" />
                    <h1>New user</h1>
                </div>
            </div>
            <div class="ui-g">
                <div class="ui-g-12">
                    <p:inputText value="#{newUserView.email}" placeholder="Username or e-mail"/>
                </div>
            </div>
            <div class="ui-g">
                <div class="ui-g-12">
                    <p:password value="#{newUserView.password}" placeholder="Password"/>
                </div>
            </div>
            <div class="ui-g">
                <div class="ui-g-12">
                    <p:commandButton value="Create" action="#{newUserView.validateNewUser()}"/>
                    <p:spacer width="20px"/>
                    <p:commandButton value="Cancel" action="#{newUserView.cancel()}"/>
                </div>
            </div>
            <div class="ui-g">
                <div class="ui-g-12">
                    <p:messages autoUpdate="true"/>
                </div>
            </div>
        </h:form>
    </h:body>
</html>

VOTE/web/playground.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>VOTE</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </h:head>
    <h:body>
        <h:outputStylesheet library="css" name="styles.css"/>
        <h:outputStylesheet name="webjars/font-awesome/4.4.0/css/font-awesome.css"/>
        <h:form id="playgroundForm">
            <div class="ui-g">
                <div class="ui-g-12">
                    <p:graphicImage name="images/network64.png" />
                    <h1>Welcome to</h1>
                    <h1>"#{playgroundView.currentPlayground.name}"</h1>
                </div>
            </div>
            <div class="ui-g">
                <div class="ui-g-12">
                    <h4>Share this unique code:</h4>
                    <h2>#{playgroundView.uniqueLink}</h2>
                </div>
            </div>
            <div class="ui-g">
                <div class="ui-g-12">
                    <p:dataTable id="playgroundTable" var="row" value="#{playgroundView.rows}">
                        <p:column style="background-color: lightblue">
                            <f:facet name="header">
                                <h:outputText value="Voter"/>
                            </f:facet>
                            <h:outputText value="#{row.nickname}" rendered="#{!row.editable}"/>
                            <p:inputText placeholder="Your name" value="#{row.nickname}" rendered="#{row.editable}" style="width: 90%;"/>
                        </p:column>
                        <p:columns var="choice" value="#{playgroundView.choices}" id="columnstest">
                            <f:facet name="header">
                                <h:outputText value="#{choice.value}"/>
                                <h:outputText value="#{playgroundView.getNumberOfVotesForChoice(choice)}" 
                                              style="float: right; color: dodgerblue;"/>
                            </f:facet>
                            <p:commandButton icon="fa fa-check" class="iconButton" style="width: 100% !important"
                                             actionListener="#{playgroundView.updateVote(row.nickname, choice, false)}" 
                                             update=":playgroundForm:playgroundTable"
                                             rendered="#{row.choiceVoteBindings.get(choice)}"/>
                            <p:commandButton icon="nothing" class="iconButton"  style="width: 100% !important"
                                             actionListener="#{playgroundView.updateVote(row.nickname, choice, true)}" 
                                             update=":playgroundForm:playgroundTable"
                                             rendered="#{!row.choiceVoteBindings.get(choice)}"/>
                        </p:columns>
                    </p:dataTable>
                </div>
            </div>
            <div class="ui-g">
                <div class="ui-g-12">
                    <p:commandButton value="Submit" action="#{playgroundView.reload()}"/>
                    <p:spacer width="20px"/>
                    <p:commandButton value="Back" action="#{playgroundView.back()}" rendered="#{playgroundView.buttonBackVisible}"/>
                    <p:commandButton value="Log in" action="#{playgroundView.toLogin()}" rendered="#{!playgroundView.buttonBackVisible}"/>
                </div>
            </div>
        </h:form>
    </h:body>
</html>

VOTE/web/playgrounds.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>VOTE</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </h:head>
    <h:body>
        <h:outputStylesheet library="css" name="styles.css"/>
        <h:outputStylesheet name="webjars/font-awesome/4.4.0/css/font-awesome.css"/>
        <h:form id="playgroundsForm">
            <div class="ui-g">
                <div class="ui-g-12">
                    <p:graphicImage name="images/network64.png" />
                    <h1>Your polls</h1>
                </div>
            </div>
            <div class="ui-g">
                <div class="ui-g-12">
                    <p:dataTable var="playground" id="playgroundsTable"
                                 value="#{playgroundsView.playgrounds}" 
                                 selection="#{playgroundsView.selectedPlayground}" 
                                 selectionMode="single"
                                 rowKey="#{playground.id}"
                                 emptyMessage="No polls yet, create one!"
                                 style="max-width: 350px;">
                        <p:ajax event="rowSelect" listener="#{playgroundsView.navigateToPlayground()}"/>
                        <p:column headerText="Polls">
                            <h:outputText value="#{playground.name}"/>
                            <p:commandButton icon="fa fa-remove" class="iconButton"
                                             actionListener="#{playgroundsView.removePlayground(playground)}" 
                                             update=":playgroundsForm:playgroundsTable"/>

                        </p:column>
                    </p:dataTable>
                </div>
            </div>
            <div class="ui-g">
                <div class="ui-g-12">
                    <p:commandButton action="#{playgroundsView.navigateToNewPlayground()}" value="New poll"/>
                </div>
            </div>
        </h:form>
    </h:body>
</html>